### ISSUE TITLE
Hoofdstuk: validatie

### ISSUE THREAD

**Issue by fhb1990** [Geonovum/inspire-handreiking#10]
- Zijn de issues inderdaad verholpen sinds september 2020? **PB** issue-nr 29 staat nog steeds open.
- Bij info over de linkagechecker kan documentatie hierover worden toegevoegd over hoe de linkage tot stand komt. Een link naar die ene powerpoint bijvoorbeeld. **PB** Het is niet duidelijk welke ppt, maar [dit](https://inspire-geoportal.ec.europa.eu/files/INSPIRE_Geoportal_process_for_data-service_linking_v1.0.pdf) is als link toegevoegd

**Comment by PB-GNM** [comment]
7    2e alinea laatste zin actualiseren wordt --> is
7.3 Hier staat dat je de NL validator moet gebruiken. Dat is in strijd met wat bij 7 staat.
7.3 Waarom in Italic?
7.3 "Themetic Viewer" --> "INSPIRE Geoportal"
7.3 Waarom worden hier alle validators nog apart genoemd terwijl ze allemaal dezelfde link hebben:  voorstel: hele tabel weg of behouden, maar dan met de codes, zodat dataproviders snel kunnen zien waar het probleem zit als er iets gemeld wordt op basis van die codes.
7.4.2 zijn inmiddels alle validaties op de schema's van alle thema's beschikbaar?
7.5 alle issues moeten nagelopen worden op de vraag wat de status ervan is.
7.6 Als tabel bij 7.3 weg, dan hier tekst er op aanpassen
7.6 Misschien screenshot toevoegen van linkchecker?

**Comment by PB-GNM** [comment]
Alle opmerkingen over validatie zijn verwerkt.
