### ISSUE TITLE
2 scenario's voor metadata en GetCapabilities van services: wordt 2e nog wel gebruikt? 

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/inspire-handreiking#21]
5.2.2.2 Wordt scenario 2 eigenlijk wel gebruikt? Wanneer kies je voor 1 en wanneer voor 2

**Comment by idevisser** [comment]
het is een optie die ook in de INSPIRE TG is uitgewerkt...maar je bent nog steeds verplicht de metadata te publiceren. Als er door service beheerders geen automatische transformatie van metadata in extended capabilities naar XML wordt uitgevoerd is het dubbel werk om ook in de extended capabilities bij te houden
