### ISSUE TITLE
Hands-on paragraaf/hoofdstuk: hoe gebruik je INSPIRE datasets 

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#25]
EU INSPIRE geoportal en Qgis plugin (zie ook rapportje Gineke)
Ook kijken naar documenten van Pieter mbt Usecase Proximity statistics

**Comment by wboersma** [comment]
Voorstel: apart hoofdstuk na M&R. Nog even nadenken welke aspecten we willen opnemen:
- EU INSPIRE Geoportal: data zoeken -> check soms ook nationale portalen in de lidstaten
- QGis plugin voor NLse data
- PDOK plugin ook noemen?
-

**Comment by idevisser** [comment]
Lijkt me een goede plek, na monitoring en reporting
@wboersma Is er op EU nivo nog iets met de QGIS INSPIRE plugin gedaan?
@PB-GNM kun jij deze oppakken na de update van 25 maart?

**Comment by wboersma** [comment]
M.b.t. vraag van Ine, nee op E-nivo is er niks meer meegedaan. Robert Tomas was er toen wel enthousiast over, maar het is niet verder opgepakt. Maar we kunnen het als idee opperen bij de EU helpdesk of MIG-T?

M.b.t. vraag van Pieter via de mail: de andere issues willen we graag deze week oplossen, zodat we nog mee gaan met de publicatie naar docs die blijkbaar op 25 maart is gepland.  Dit issue dient dus daarna opgepakt worden voor een latere release.

**Comment by PB-GNM** [comment]
https://github.com/Geonovum/inspire-handreiking/blob/main/md/gebruik.md
is in grote lijn klaar voor een eerste review, maar moet daarvoor eerst nog in werkdocument gehangen worden via de index.html en/of config file.

**Comment by PB-GNM** [comment]
Ik heb het hoofdstuk gebruik geplaatst in de werkversie in H9.

**Comment by wboersma** [comment]
Ik heb hoofdstuk 9 globaal gelezen en ik zit een beetje te worstelen met wat er nu in moet komen. Voor nu een aantal opmerkingen:

1. Het betreft INSPIRE data, dus de alinea over opendata zou ik weghalen. Dit is verwarrend.
2. Ik zou het hoofdstuk opdelen in twee paragrafen: 
             - Gebruik van Nederlandse data 
             - Gebruik van Europese data uit het INSPIRE geoportal (incl. subparagraaf met de andere Europese dataportalen)
             - In elke paragraaf zou ik dan het zoeken en het gebruiken beschrijven in het portaal (dus met name viewen). 
             - En dan tot slot nog een aparte paragraaf over het gebruiken (daadwerkelijk downloaden) via QGIS. Dan hier onderscheid weer naar de NLse data (via INSPIRE QGIS plugin) en de Europese data.
3. De paragraaf  Europese data in het INSPIRE geoportal zou ik wat uitgebreider beschrijven. Zoals je meerdere ingangen hebt om de data te zoeken (via meerdere ingangen, etc). Dat je via de icoontjes gemakkelijk kunt zien of hoe de data beschikbaar is (metadata, download, view, regionaal of landsdekkend, etc.) Dat je de metadata automatisch naar het Engels kan vertalen. En hoe je de data kunt viewen en downloaden.
4. Je hebt inderdaad belemmeringen, maar die wil ik hier niet vinden eigenlijk. Je moet ze omzetten in handige tips om het de gebruiker juist makkelijker te maken. Maar dit heeft niet alleen te maken met het vinden, maar ook met het gebruiken van de data. Dus nog even goed kijken welke punten je meeneemt bij het vinden en welke je meeneemt bij het gebruiken van de data.
5. De paragraaf over algemene tips is eigenlijk een beetje dubbel met paragraaf https://geonovum.github.io/inspire-handreiking/#inspire-helpdesk. Dus we moeten even kijken of hem wel of niet opnemen. Daarnaast is de EU helpdesk niet echt ervoor om vragen te stellen over het gebruik van de data...

Best lastig om alles goed te verwoorden. Misschien handiger om een overleg even in te plannen hierover.

**Comment by idevisser** [comment]
Hoi,

Hierop nog wat aanvullingen van mij;



  1.  Omzetten in tips ipv “let op”:
Bijvoorbeeld het zinnetje;
…kan hiervoor een vinkje in de linker kolom geplaatst worden bij Categorie "Inspire". Let op: dit kan nog niet op de startpagina van NGR, maar pas nadat er eerst een ander zoek criterium is opgegeven.
Dit kun je ook zo verwoorden;
Kan je filteren op de zoekresultaten met de categorie INSPIRE.


  1.  Het gaat hier over INSPIRE data die wordt in GML geleverd, daar worden de INSPIRE datamodellen voor gebruikt en is ETRS89 verplicht. (nu te veel slagen om de arm, door woorden als soms, leiden vaak…etc.) neem de INSPIRE data als uitgangspunt.
  2.  Maak eventueel een onderscheid in as is en geharmoniseerd.
  3.  Wees zuiver in wat je benoemt bij grensoverschrijdende problemen, daar geen andere zaken in opnemen.


En wat losse opmerkingen

  *   Werkt het om  het feature type te gebruiken als zoekterm?
  *   Voor INSPIRE data mag het niet dat er eerst iets ondertekend worden voordat je het mag downloaden.

Groet Ine

Van: Wideke Boersma ***@***.***>
Verzonden: maandag 2 mei 2022 14:19
Aan: Geonovum/inspire-handreiking ***@***.***>
CC: Ine de Visser ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Geonovum/inspire-handreiking] Hands-on paragraaf/hoofdstuk: hoe gebruik je INSPIRE datasets (Issue #25)


Ik heb hoofdstuk 9 globaal gelezen en ik zit een beetje te worstelen met wat er nu in moet komen. Voor nu een aantal opmerkingen:

  1.  Het betreft INSPIRE data, dus de alinea over opendata zou ik weghalen. Dit is verwarrend.
  2.  Ik zou het hoofdstuk opdelen in twee paragrafen:
- Gebruik van Nederlandse data
- Gebruik van Europese data uit het INSPIRE geoportal (incl. subparagraaf met de andere Europese dataportalen)
- In elke paragraaf zou ik dan het zoeken en het gebruiken beschrijven in het portaal (dus met name viewen).
- En dan tot slot nog een aparte paragraaf over het gebruiken (daadwerkelijk downloaden) via QGIS. Dan hier onderscheid weer naar de NLse data (via INSPIRE QGIS plugin) en de Europese data.
  3.  De paragraaf Europese data in het INSPIRE geoportal zou ik wat uitgebreider beschrijven. Zoals je meerdere ingangen hebt om de data te zoeken (via meerdere ingangen, etc). Dat je via de icoontjes gemakkelijk kunt zien of hoe de data beschikbaar is (metadata, download, view, regionaal of landsdekkend, etc.) Dat je de metadata automatisch naar het Engels kan vertalen. En hoe je de data kunt viewen en downloaden.
  4.  Je hebt inderdaad belemmeringen, maar die wil ik hier niet vinden eigenlijk. Je moet ze omzetten in handige tips om het de gebruiker juist makkelijker te maken. Maar dit heeft niet alleen te maken met het vinden, maar ook met het gebruiken van de data. Dus nog even goed kijken welke punten je meeneemt bij het vinden en welke je meeneemt bij het gebruiken van de data.
  5.  De paragraaf over algemene tips is eigenlijk een beetje dubbel met paragraaf https://geonovum.github.io/inspire-handreiking/#inspire-helpdesk. Dus we moeten even kijken of hem wel of niet opnemen. Daarnaast is de EU helpdesk niet echt ervoor om vragen te stellen over het gebruik van de data...

Best lastig om alles goed te verwoorden. Misschien handiger om een overleg even in te plannen hierover.

**Comment by idevisser** [comment]
Helaas toch nog wel een heel aantal opmerkingen. Graag volgende aanpassen;

1. In 9.1.1 Vinden van NL-data, de zin
 "De meeste Nederlandse dataproviders van (INSPIRE-) geoinformatie beschrijven hun datasets via metadata en publiceren dat in het [Nationaal Georegister](https://www.nationaalgeoregister.nl/) (NGR)." aanpassen in: INSPIRE datasets zijn beschreven met metadata die gepubliceerd is in het NGR. 
2. In 9.1.1 Vinden van NL-data,  de zin "Veel data komt meerdere keren voor maar dan als verschilend brontype. Meestal als dataset, maar ook vaak als verschillende services. Om deze dubbeling er uit te halen " aanpassen in: Zowel de dataset als de view en download services zijn voorzien van metadata. Er kan naar de dataset metadata (of service metadata) gegaan worden door te filteren op brontype.
3. In 9.1.1 Vinden van NL-data,,  Ik mis in deze paragraaf  een beschrijving van het uitgebreid zoeken op de INSPIRE thema's.
4.  In 9.1.2 Vinden van EU-data, de zin "In dit portaal kan vervolgens gekozen worden uit Priority Datasets Viewer en INSPIRE Thematic Viewer. De linker is voor datasets die ook onder een Europese rapportageverplichting vallen. De rechter is specifiek voor INSPIRE datasets."aanpassen in: De INSPIRE Thematic Viewer geeft toegang tot alle datasets die onder INSPIRE vallen. De Priority Dataset Viewer geeft toegang tot de INSPIRE datasets, die ook voor milieu rapportage verplichtingen gebruikt worden.
Hierin kan onder andere gezocht worden via de milieu wetgeving waarvoor gerapporteerd wordt. In de INSPIRE Thematic Viewer.... etc.
5. De zin "Wanneer het gaat om grensoverschrijdend gebruik is het verstandig eerst te zoeken naar datasets die geharmoniseerd zijn naar het betreffende INSPIRE-thema. Als datasets geharmoniseerd zijn zullen ze beter op elkaar aansluiten. Zowel ruimtelijk als thematisch. Als de geharmoniseerde data niet te vinden is, kan de niet geharmoniseerde data ([AsIs-data](https://geonovum.github.io/inspire-handreiking/#as-is-versus-geharmoniseerde-data)) ook voldoende zijn voor het gebruiksdoel." aanpassen in : Voor grensoverschrijdend gebruik heeft geharmoniseerde data,  waarschijnlijk de voorkeur. geharmoniseerde data sluit ruimtelijk als thematisch beter op elkaar aan. 
6. de zin "Wanneer het niet te vinden is via het INSPIRE Geoportal, .." aanpassen in : Wanneer de dataset ....
7. lokale catalogi aanpassen in nationale of regionale catalogi
8. Tips voor het vinden van Europese data: Omdat de metadata vaak in de lokale taal is, aanpassen in ; zoeken via de INSPIRE thema's
9.  Tips voor het vinden van Europese data: Omdat de metadata vaak in de lokale taal is, aanvullen Dat je de metadata automatisch naar het Engels kan vertalen.
10. in 9.3.1 Viewen NL-data via NGR zou 1 voorbeeld nemen en die uitwerken , dus alleen land use of alleen stads en dorpsgezichten
11. 9.3.3 Downloaden mis hier of in vorige paragraaf dat in het EU geoportal slechts een gedeelte van de dataset wordt gedownload (of is dat inmiddels verholpen?) 
12. QGIS basisfunctionaliteit, willen we dit opnemen??? lijkt me dat we vooral focussen op gebruik INSPIRE data dmv de plugin
13. PDOK-PDOK plugin, willen we dit opnemen?

**Comment by PB-GNM** [comment]
Ik heb alle nieuwe opmerkingen van Ine hierboven verwerkt.

Over de 2 discussiepunten (12 en 13 van Ine haar opmerking hierboven):
Voor mijn gevoel is de QGIS basisfunctionaliteit (12) voor het benaderen van INSPIRE services een heel relevant onderwerp, omdat je dat nodig hebt als je niet Nederlandse INSPIRE-services wil laden, maar ook omdat daar nog net weer wat meer mee kan dan met alleen de INSPIRE plugin, zoals het laden van een style of een filter toepassen.
Het nut van de PDOK plugin (13) voor INSPIRE-datasets kan ik minder goed verdedigen dus daar sta ik neutraal tegenover.

**Comment by wboersma** [comment]
Ik heb de tekst gelezen en de tekst al aangepast op schrijffouten die ik tegenkwam en in lijn gebracht met hoe begrippen in de rest van de handreiking worden beschreven. 

Twee openstaande punten van Ine:
- QGIS basisfunctionaliteit, willen we dit opnemen??? lijkt me dat we vooral focussen op gebruik INSPIRE data dmv de plugin. Eens met Ine, je verwacht dat de gebruiker dit weet. Je wilt juist hier de focus op de INSPIRE QGIS plugin. Dus paragraaf 9.3.5 Gebruik in GIS in NL hernoemen naar 9.3.5 INSPIRE QGIS plugin
- PDOK-PDOK plugin, willen we dit opnemen? Eens met Ine, dit niet opnemen.

Hieronder nog een aantal opmerkingen:
1. De paragraaf 9.2 Bestuderen metadata is eigenlijk onderdeel van het vinden van data. Dus ik zou hier 9.1.3 van maken.
2. In paragraaf 9.2 zin 'Maar eigenlijk alles wat hierover beschreven staat in het hoofdstuk over [metadata](https://geonovum.github.io/inspire-handreiking/#metadata).' vind ik een vreemde zin. Zou ik weghalen, want als je op de link klikt, verwacht je antwoorden over de aspecten die benoemd, maar die vind je niet in het hoofdstuk metadata. 
3. Ik vind deze tekst *'De directe URL voor het downloaden van de zip-file via een Atomfeed is te vinden via de service-feed. Dat is een xml-file waarvan de URL in de metadata van de dataset en de Atom service moet staan. In deze xml file staat dan dan een link naar de dataset-feed. Die bevat dan de directe URL voor het downloaden van de zip-file. Het komt voor dat deze link al direct is opgenomen in de service-feed.'* erg verwarrend. Spreekt het niet voor zich als je op de links klikt in het NGR of INSPIRE geoportal? Zo ja, dan zou ik deze tekst weghalen. Soms is juist minder tekst duidelijker.
4.  Paragraaf 'Gebruik in GIS algemeen' zou ik starten dat de INSPIRE datasets via view- en downloadservices in bijvoorbeeld QGIS maar ook in ESRI producten direct kunnen gebruiken worden. Dat we dat hier niet verder beschrijven, maar verwijzen naar een algemene ESRI of QGIS pagina met handleiding (https://docs.qgis.org/3.22/nl/docs/user_manual/index.html of https://www.esri.nl/nl-nl/home). En daarna dan je algemene tips over CRS, etc.
5. De tip over complex GML dat je iets extra's moet installeren zou ik bij de INSPIRE QGIS plugin plaatsen.
6. Viewen en downloaden via browser. Hier geef je aantal voorbeelden. Ik heb nu de vraag of je NGR of INSPIRE geoportal ook bij deze links kan komen. Of moet je ze zelf samen stellen. Indien dat laatste het geval is, dan vraag ik me de meerwaarde van deze 2 paragrafen af. Want als beginnende gebruiker ga je dit dan niet zo snel doen. Dan is het toch het handigst om dit via Qgis te doen.

**Comment by PB-GNM** [comment]
@wboersma : zijn er situaties dat die ***QGIS GML Application Schema Toolbox*** ook nodig is voor het gebruik van de QGIS-plugin? Zo ja, dan moet het inderdaad daar al genoemd worden, maar anders laat ik het zo. Het staat nu als laatste omdat ik de QGIS-plugin nu eerder behandel.

**Comment by wboersma** [comment]
@PB-GNM dat weet ik niet meer zeker. Maar prima om het als laatste op te nemen.

**Comment by wboersma** [comment]
Ik heb de tekst gereviewd. De laatste 2 paragrafen (downloaden en viewen via browser) blijf ik lastig vinden en is denk ik meer voor de expert gebruiker.

**Comment by wboersma** [comment]
Kan deze nu gesloten worden?

**Comment by PB-GNM** [comment]
Wat mij betreft wel.

**Comment by idevisser** [comment]
ik heb beooprdelen metadata eruit gehaald, mag verwachtten dat mensen met geo kennis die stap kennen
