### ISSUE TITLE
Services, domain model

### ISSUE THREAD

**Issue by idevisser** [Geonovum/inspire-handreiking#26]
verwijzing naar domain model eruit halen, dit is verouderd....
zou het eenvoudige plaatje ook niet hier neerzetten, wellicht verhelderend bij het eerste hoofdstuk oid
**PB:** Ik heb het achter het stappenplan geplakt, omdat daar ook voor het eerst over data, metadata en service gepraat wordt.

**Comment by idevisser** [comment]
Zou hier plaatje en toelichting opnemen over  categorieen SDS, het bepalen van SDS, de stroomschema's aan eind van hoofdstuk laten staan.

**Comment by PB-GNM** [comment]
Kan dit issue nu gesloten worden?
