### ISSUE TITLE
ppt met data service koppeling

### ISSUE THREAD

**Issue by idevisser** [Geonovum/inspire-handreiking#35]
hebben we die info al ergens opgenomen?

**Comment by wboersma** [comment]
Nee volgens mij niet. Waar wil je hem neerzetten? Bij de linkchecker?

**Comment by idevisser** [comment]
ja, lijkt me handig, ook delen van de sheets in de tekst van de handreiking opnemen

**Comment by idevisser** [comment]
ik update  de ppt (was van 2018) en zet hem bij linkchecker

**Comment by idevisser** [comment]
ppt staat er, nog delen uit ppt direct in handreiking over nemen

**Comment by wboersma** [comment]
@idevisser, kunnen we dit punt sluiten of wil je nog delen overnemen in de handreiking? Anders graag sluiten.

**Comment by wboersma** [comment]
Actie Pieter: ppt  teksten opnemen in de handreiking zelf. Ppt staat hier: https://geonovum.github.io/inspire-handreiking/#link-checker

**Comment by PB-GNM** [comment]
Ik heb de ppt verwerkt onderin het validatie hoofdstuk.

Daarbij heb ik nog de volgende vragen:
1. Check 3: Bij WFS stond de 3e check de link naar metadata service niet in de tekst, maar wel in het plaatje. Ik heb hem toegevoegd in de tekst. Is dat ok?
2. Check 3: SOS: Waarom is er geen link naar de metadata van de service en dataset?
3. Check 3: WCS: Waarom is er geen link naar de metadata van de service?
4. Check 4: WMS: Waarom is er bij de WMS geen link naar de bronidentifier van de dataset via element SpatialDataSetIdentifier zoals wel bij WFS?
5.  Check 9: Daar staat dat je maar 1 dataset per WFS mag ontsluiten, maar wat is eigenlijk de definitie van een dataset? Voor SU worden bv 3 gpkg files in 1 atom met 3 downloads en en in 1 WFS met 3 lagen aangeboden en daar staat 1 dataset metadata record voor beschreven. mag dat dan wel of niet?

Wanneer er een antwoord is op vraag 2 en 3, moet dat waarschijnlijk nog verwerkt worden, dus ik kan hem nog niet sluiten.

**Comment by idevisser** [comment]
Het gaat in dit stuk om de link tussen de service en de dataset. (en daarmee het zichtbaar worden in het EU geoportal). Bij WFS/SOS /WCS wordt die link niet gelegd via de metadata van de service, vandaar wordt deze niet genoemd.
Bij WMS verloopt de koppeling via de metadatURL en niet via identiefier. Vandaar dat er andere elementen zijn opgenomen in dit stuk.
De vereiste voor 1 dataset per download is specifiek voor WFS en niet voor ATOM. Vanuit de WFS kan maar naar 1 identifier van 1 dataset verwezen worden, de andere datasets ontsloten in de WFS zijn dan niet vindbaar in het EU geoportal.
ons advies voor ATOm is om het aantal ook beperkt te houden, in ieder geval van maar één organisatie en bij prioriaire datasets liefst apart.

Ik loop het stuk na en pas de dingen aan waar nodig.

**Comment by PB-GNM** [comment]
De hele Geoportaltips.ppt is er nu in verwerkt.
