### ISSUE TITLE
Twee aparte hoofdstukken maken van data en dataharmonisatie

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#36]
Ik heb nog even door de tekst/inhoudsopgave gekeken en het lijkt mij toch beter om de stuk tekst over soorten INSPIRE data als apart hoofdstukje op te nemen. Dan komt het hoofdstuk dataharmonisatie ook beter tot z'n recht. 
@PB-GNM , @idevisser graag jullie mening.

**Comment by idevisser** [comment]
is oke zo
