### ISSUE TITLE
encodings

### ISSUE THREAD

**Issue by idevisser** [Geonovum/inspire-handreiking#37]
nu gml
wat mogelijk met geopackage
regels waarmee het wel anders mag
tno ppt

**Comment by wboersma** [comment]
@idevisser, kun je nog even goed de paragraaf encodings (https://geonovum.github.io/inspire-handreiking/#encodings-bestandsformaten) doorlezen.
Paar punten in ieder geval: 
- er wordt verwezen naar de mediatypes. Klopt dit nog wel? Ik heb nu een kopje GML aangemaakt, maar moet dit stukje tekst over mediatypes dan naar andere encodings?
- er is ook nog een gp coverages encoding, moeten we daar ook niet naar verwijzen
-

**Comment by idevisser** [comment]
aangepast
