### ISSUE TITLE
toevoegen aan dataharmo register voor applicatieschema's etc

### ISSUE THREAD

**Issue by idevisser** [Geonovum/inspire-handreiking#38]
- De INSPIRE infrastructuur bevat een aantal elementen waarvoor een duidelijke beschrijving nodig is en de mogelijkheid om ernaar te verwijzen door middel van unieke identificatoren. Voorbeelden van dergelijke elementen zijn de INSPIRE themas, codelijsten, applicatie schemas of zoek diensten. Registers bieden een manier aan om identificatoren toe te wijzen aan deze elementen en aan hun labels, definities en beschrijvingen (in verschillende talen). Het <a href="https://inspire.ec.europa.eu/registry/" target="_blank">INSPIRE register</a> biedt een centraal toegangspunt voor een aantal centraal beheerde INSPIRE registers. De inhoud van deze registers is gebaseerd op de INSPIRE richtlijn, de uitvoerings regels en de technische handleidingen.

**Comment by wboersma** [comment]
In hoofdstuk 1 staat het INSPIRE register al wel beschreven. Zie: https://geonovum.github.io/inspire-handreiking/#inspire-registry. Ik heb trouwens de Engelse term gehanteerd (zie ik nu). Wil je dit nog een keer opnemen bij dataharmonisatie of verwijzen naar hoofdstuk 1.

**Comment by idevisser** [comment]
dan is het oke, was even voor mij een issue om te zorgen dat dit niet tussen wal en schip valt
