### ISSUE TITLE
Nog goed kijken of alle plaatjes leesbaar zijn. Anders nieuwe versies maken

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#40]
Sommige plaatjes in view service paragraaf lastig te lezen namelijk.

**Comment by idevisser** [comment]
@PB-GNM pak jij deze op?

**Comment by PB-GNM** [comment]
Ik heb de plaatjes onderzocht.

De eerste heb ik kunnen verbeteren ([wms.png](https://github.com/Geonovum/inspire-handreiking/blob/main/media/Wms.png))

De andere 2 ([scenario1.png](https://github.com/Geonovum/inspire-handreiking/blob/main/media/Scenario1.png) en [scenario_2.png](https://github.com/Geonovum/inspire-handreiking/blob/main/media/Scenario_2.png)) kan ik niet eenvoudig verbeteren. Bestaan hier betere versies van, of is het een idee om Tanne te vragen deze opnieuw te ontwerpen?

**Comment by PB-GNM** [comment]
Ik doe ook nog 2e plaatje uit https://geonovum.github.io/inspire-handreiking/#processtappen uit mail Wideke.

**Comment by PB-GNM** [comment]
De volgende plaatjes zijn aangepast:
scenario1, scenario_2, wms en wfs.png
