### ISSUE TITLE
Nieuwe TG metadata op github: hiernaar toe verwijzen in hoofdstuk metadata

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#41]
Nav de MIG_T:
@idevisser, Is het akkoord dat we linken naar de nieuwe TG metadata op github in hoofdstuk metadata. Dit is nu de laatste versie namelijk. 
Zie https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc

Ik zie nu pas dat we helemaal niet verwijzen naar deze TG in het hoofdstuk metadata. @idevisser, klopt dat?

**Comment by idevisser** [comment]
We verwijzen alleen naar het NL profiel omdat ze  daarmee gelijk aan INSPIRE kunnen voldoen.
