### ISSUE TITLE
Downloadservices: OGC SensorThings API nog toevoegen in paragraaf 5.4??

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#42]
Moet in het rijtje van 5 download services niet ook OGC SensorThings API worden opgenomen. Is een endorsed GP namelijk. Zie https://inspire.ec.europa.eu/good-practice/ogc-sensorthings-api-inspire-download-service

**Comment by wboersma** [comment]
Betreft paragraaf 5.4

**Comment by idevisser** [comment]
ja lijkt me wel zo volledig.
@pieter, zet jij de  OGC SensorThings API in paragraaf 5.4 erbij?

**Comment by wboersma** [comment]
Al gedaaan
