### ISSUE TITLE
INSPIRE en CRS

### ISSUE THREAD

**Issue by idevisser** [Geonovum/inspire-handreiking#46]
1. Verwijzen naar de CRS handreiking https://docs.geostandaarden.nl/crs/crs/#mogelijke-crs-en-binnen-inspire

2. Opnemen stuk text (zie eerder advies hieronder) over CRS en INSPIRE oa over hoogte, **check met 1** en https://github.com/INSPIRE-MIF/technical-guidelines/issues/27 ;

Introductie & aanleiding
Voor enkele datasets, zoals voor het thema Hoogte (Elevation), is het nodig om data voor INSPIRE te
publiceren in 3D. INSPIRE vereist dat data conform de Dataspecificaties geharmoniseerd worden. In de
Dataspecificaties voor Hoogte staat een lijst van meerdere (3D) coördinaatreferentiesystemen (CRS) die
gebruikt mogen worden.
Vanwege de harmonisatie van het AHN, wenst het Waterschapshuis een uitspraak over het te gebruiken CRS.
Het heeft de voorkeur dat andere Nederlandse dataproviders die in 3D data gaan/willen leveren, dat met
hetzelfde CRS gaan doen.
Dit memo bevat een aanbeveling, met onderbouwing, voor gebruik van ETRS89+EVRS als 3D CRS voor de
publicatie van gegevens op land in Nederland als die in 3D geleverd moeten worden, conform INSPIRE. De
INSPIRE Klankbordgroep en Stuurgroep wordt gevraagd een besluit te nemen over deze aanbeveling.

Verplichtingen INSPIRE versus NAP hoogtes
De INSPIRE Implementing Rules 2, de juridisch bindende regels, stellen het hoogtesysteem EVRS (European
Vertical Reference System) verplicht als het te gebruiken systeem voor de verticale component van gegevens
op land bij een samengesteld coördinaatreferentiesysteem.
In de Dataspecificatie “Data Specification on Coordinate Reference Systems” 3 en de Dataspecificatie voor
Hoogte / Elevation 4 wordt dit uitgewerkt en wordt voorgeschreven dat één van de volgende CRSen gebruikt
dient te worden voor publicatie:
• ETRS89-XYZ (EPSG::4936)
• ETRS89 (EPSG::4937)
• ETRS89+EVRS (EPSG::7409)
Bij raadpleging van Nederlandse specialisten op het gebied van CRSen en geodetische infrastructuur , bleek
ETRS89+EVRS de voorkeur te hebben van deze drie.
Maar ook bleek dat NAP als hoogtesysteem in principe de voorkeur heeft boven EVRS op dit moment. Redenen
hiervoor zijn:
• NAP is meer herkenbaar voor gebruikers;
• Het huidige EVRS kent (maximaal) enkele centimeters afwijking t.o.v. NAP;
• de EVRS-realisatie is nog niet volledig uitontwikkeld, er komt nog een nieuwe realisatie aan die beter
aansluit op het NAP met een afwijking van enkele millimeters.
NAP is strikt genomen echter geen geldig hoogtesysteem in INSPIRE. In die zin kan NAP dus niet gebruikt
worden voor geharmoniseerde data in de context van INSPIRE.
NAP en EVRS: kleine verschillen
Hier staat tegenover dat het verschil tussen NAP en EVRS klein is (verschil van maximaal een paar centimeter).
Voor veel datasets is dat verschil kleiner dan de nauwkeurigheid van de data zelf. In zo’n geval kan NAP gezien
worden als de Nederlandse realisatie van EVRS. Met andere woorden: hoogtes opgegeven in NAP hoeven niet
getransformeerd te worden, als de hoogte component van de data minder nauwkeurig is dan 5 centimeter.
Voor AHN bijvoorbeeld geldt dit (het AHN heeft een nauwkeurigheid van 5 centimeter) en kan de hoogte in NAP
worden beschouwd als de hoogte in EVRS. Andersom geldt dat hoogtes in EVRS op land in Nederland als NAP
hoogte kunnen worden geïnterpreteerd, als de nauwkeurigheid van de verticale component groter is dan 5
centimeter.
Aanbeveling: gebruik EPSG::7409 voor hoogte data
Voor Nederlandse dataproviders die voor INSPIRE in 3D coördinaten publiceren is nu de aanbeveling dat:
1. Bij het leveren van geharmoniseerde data, de coördinaten worden uitgedrukt in het samengestelde CRS
ETRS89+EVRS, met EPSG code EPSG::7409 (http://www.opengis.net/def/crs/EPSG/0/7409).
• De Download Services dienen de data dus (in ieder geval) in deze EPSG-code aan te bieden.
2. Als de brondata hoogtes bevat in NAP, deze hoogtes zonder transformatie gepubliceerd kunnen worden
als EVRS hoogtes, op voorwaarde dat:
• het gegevens op land in Nederland betreft
• de nauwkeurigheid van de verticale component (hoogte) groter is dan 5 centimeter.
• er in de metadata beschreven is dat er geen transformatie van NAP naar EVRS hoogtes heeft
plaatsgevonden
4. De nauwkeurigheid (ook van de hoogte) wordt opgenomen in de metadata van de dataset, om
duidelijkheid te scheppen aan de eindgebruiker over de interpretatie ervan.
Wanneer een dataprovider geen transformatie gebruikt, maakt men gebruik van de hoogte uit het NAP en
publiceert deze als ETRS89+EVRS. Hiermee ontstaat een nauwkeurigheid van maximaal 5 cm, wanneer men
een hogere nauwkeurigheid wenst, moet men transformeren.
Kanttekeningen:
1. Voor datasets met een hogere nauwkeurigheid is dus wel degelijk een transformatie nodig en kunnen
de NAP hoogtes dus niet direct als EVRS hoogtes worden beschouwd. Alternatief is om te accepteren dat
de hoogtes in EVRS minder nauwkeurig weergegeven worden. Als dat acceptabel is, volstaat het om de
data niet te transformeren, maar is het wel noodzakelijk in de metadata te vermelden dat de hoogte een
lagere nauwkeurigheid heeft.
2. Als er een nieuwe EVRF-realisatie wordt gepubliceerd, zal de aanbeveling mogelijk herzien worden. De
Dataspecificatie voor Coördinaatreferentiesystemen voorziet ook dat dit kan gebeuren (hoofdstuk 5):
3
“Future solutions of the EVRF will constitute an improvement and are considered realisations of the
EVRS.”
Dergelijke realisaties krijgen een andere EPSG code. In die zin valt te verwachten dat als er nieuwe
EVRF-realisatie komt, er ook een andere EPSG code gebruikt zal moeten worden.
3. Het staat data providers natuurlijk vrij om naast een levering voor INSPIRE in EPSG:7409, ook in een
ander systeem te (blijven) publiceren. Bijvoorbeeld RD+NAP, met code EPSG:7415

1 Voor bathymetrie speelt dit vraagstuk niet, er wordt gebruik gemaakt van een ander stelsel en er
gelden andere voorwaarden op zee. De Dienst der Hydrografie is geraadpleegd.
2 	Zie Nederlandstalige versie: https://eur-lex.europa.eu/legal
content/NL/TXT/HTML/?uri=OJ:L:2010:323:FULL&from=EN, paragraaf 1.3.3.	
3 	Te downloaden via https://inspire.ec.europa.eu/id/document/tg/rs
4 Te downloaden via https://inspire.ec.europa.eu/id/document/tg/el

**Comment by PB-GNM** [comment]
Ik heb het verwerkt in https://github.com/Geonovum/inspire-handreiking/blob/main/md/crs.md .
Als jullie het OK vinden stel ik voor dat we dit opnemen in hoofdstuk 3 over Dataharmonisatie tussen de laatste paragraven validatie en geometrie.

**Comment by idevisser** [comment]
text is oke, graag opnemen in de publicatie versie

**Comment by PB-GNM** [comment]
Opgenomen in hoofdstuk 3 over Dataharmonisatie tussen de laatste paragraven geometrie en validatie.
