### ISSUE TITLE
Link werkt wel in werkversie maar niet op officiële publicatieplek

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/inspire-handreiking#47]
de link naar een voorbeeld xml werk niet in: 
https://docs.geostandaarden.nl/eu/INSPIRE-handreiking/#voorbeeldbestand-xml-voor-inspire-service-metadata
maar wel  in:
https://geonovum.github.io/inspire-handreiking/#voorbeeldbestand-xml-voor-inspire-service-metadata

**Comment by PB-GNM** [comment]
https://docs.geostandaarden.nl/eu/INSPIRE-handreiking/#voorbeeld-metadatabestand-xml-voor-inspire-dataset gaat ook fout

**Comment by wboersma** [comment]
Ik denk dat dit komt omdat de voorbeeldbestanden in de directory docs staan en niet in de directory media. Blijkbaar wordt met het publiceren naar docs.geostandaarden de directory docs niet meegenomen.

**Comment by PB-GNM** [comment]
Ik (Jan) zal deze wel even beantwoorden.

Standaard is een respec document dat gepubliceerd wordt een index.html document en komen de plaatjes uit de media folder. Er zijn dus geen andere folders (zoals docs) die mee gekopieerd worden naar docs.geostandaarden.nl. Dat verklaart waarom de voorbeeldbestanden  nu niet worden gevonden.
Nu kunnen we drie dingen doen om het op te lossen:
1)	Docs ook naar geostandaarden.nl kopieren, maar dat heeft eigenlijk niet mijn voorkeur. We wijken dan af van de standaard en moeten dan elke keer bedenken dat we de docs folder ook mee moeten kopiëren. Bovendien iets van standaarden…. Eat-your-own-dogfood …
2)	De bestanden die je wil kunnen downloaden plaats je ‘naast’ index.html, en je gebruikt in het document een relatieve link. Ook dan moeten we er aan denken dat de files mee gekopieerd moeten worden.
3)	Bijna een zelfde oplossing: de bestanden plaats je in de media folder, en link je vanuit de media folder. Dit is de standaardoplossing, en die heeft wat mij betreft de voorkeur. Elke respec beheerder zal altijd alles uit de media folder mee publiceren.
4)	Ook nog een optie is om de files op Github te laten staan, en ook van daaraf te linken. Dan hoeft er helemaal niks aan files gekopieerd te worden. Wel een addertje onder het gras: als de repo ophoudt te bestaan, of als de files uit de repo worden verwijderd heb je weer een dode link in je document…

Optie 3 is dus het veiligst. Consequentie is wel dat je dan nu het document nog een keer moet aanpassen en herpubliceren (met de juiste links naar de media folder) 

Groet,
Jan

**Comment by PB-GNM** [comment]
Ik heb alle documenten naar de media map verplaatst en alle linkjes ( 8 verspreid over 4 md bestanden) aangepast.
Bij de volgende publicatie naar doc.geostandaarden.nl zou het nu goed moeten gaan.
