### ISSUE TITLE
Versies van data toevoegen aan handreiking

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#48]
Tekst is klaar maar door de nieuwe vereisten van de HVD act nog even opnieuw bekijken, aanvullen of evt. aanpassen. Bij HVD vereisten wordt historische data iig bij aardobservatie en milieu expliciet genoemd, net als meerdere generalisatie nivo’s…

Hieronder de originele tekst:

### Aanmerken en versies van datasets
Zoals hierboven beschreven, kan om verschillende redenen een wijzging in de aanmerking plaats vinden omdat een actuelere versie van de dataset voorhanden is. De vraag is dan of de oudere versies van de dataset wel of niet beschikbaar moeten blijven voor INSPIRE. De INSPIRE richtlijn zelf stelt geen eisen m.b.t. het beschikbaar houden van data als er een nieuwe versie van de dataset wordt gepubliceerd. Het belang van het beschikbaar houden is per dataset verschillend. De ene dataset komt in aanmerking voor monitoringsdoeleinden over verschillende jaren heen, waar dat bij andere datasets niet van toepassing is.

De belangrijkste vraag is of de aangemerkte versies van de dataset nog worden gebruikt. Is er nog vraag naar de data?

Als het antwoord hierop JA is. Dan is het logisch om de datasets ook te blijven aan te bieden voor INSPIRE. De datasets blijven aangemerkt.

Als het antwoord hierop NEE is, dan kunnen de datasets afgemerkt worden voor INSPIRE. Aanvullend advies is wel dat de dataproviders kunnen overwegen om de metadata van de dataset te blijven aanbieden en in de metadata aan te geven dat de dataset opvraagbaar is bij de dataprovider.

**Comment by wboersma** [comment]
Tekst aangepast en de HVD ontwikkeling hierin meegenomen. @idevisser graag nog even review want ik heb het iets bondiger verwoord. Zie https://geonovum.github.io/inspire-handreiking/#aanmerken-en-versies-van-datasets

**Comment by wboersma** [comment]
@idevisser heb jij hier nog naar gekeken?

**Comment by idevisser** [comment]
ja, nog even implementatiewet eruit gehaald, verder oke
