### ISSUE TITLE
Harvest elke eerste maandag van de maand

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#49]
Deze tekst staat in 1.4.4 Nationaal Georegister. Deze tekst ook opnemen bij 1.4.2 Europese INSPIRE geoportal. 
En in 6.6.9 Check 9: Overige checks.
Bij overige checks staat dat wij bij veel wijzigingen een extra harvest kunnen draaien. Willen we dat nog steeds?

Ik pak dit op, maar graag wel nog antwoord op mijn vraag hoe jullie hier tegen aan kijken

**Comment by idevisser** [comment]
hmm, zijn net allemaal verschillende tekstjes. Misschien handig om ergens (bij 1.4.4 ?) alles op te nemen, zoals kijken in harvesting status en daar van de andere paragrafen naar te verwijzen.

**Comment by wboersma** [comment]
Aangepast. Bij 1.4.2 https://geonovum.github.io/inspire-handreiking/#europese-inspire-geoportal kopje harvesting toegevoegd en hier op de andere plekken in de tekst naar verwezen
