### ISSUE TITLE
Linkjes nalopen in voorbeeld metadata bestanden

### ISSUE THREAD

**Issue by arbakker** [Geonovum/inspire-handreiking#52]
Aantal links in [4.4.4 Voorbeeld metadatabestand (XML) voor INSPIRE Spatial Data Service (SDS)](https://docs.geostandaarden.nl/eu/INSPIRE-handreiking/#x4-4-4-voorbeeld-metadatabestand-xml-voor-inspire-spatial-data-service-sds)  kloppen niet, wellicht zijn het er mee:

- [`http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/availability`](http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/availability)
- [`http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/performance`](http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/performance)
- [`http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/capacity`](http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode/capacity)

Moet zijn: [`http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability`](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability) etc.

Zie ook https://github.com/Geonovum/inspire-handreiking/issues/51

**Comment by PB-GNM** [comment]
Verbeterd in https://github.com/Geonovum/inspire-handreiking/blob/main/media/Voorbeeld_Metadata_Services_2022_max.xml

Niet vergeten dat we bij de volgende publicatie ook deze media directory updaten in docs.geostandaarden.nl !
