### ISSUE TITLE
Link naar qualityOfService codelist niet correct in SDS voorbeeld md

### ISSUE THREAD

**Issue by arbakker** [Geonovum/inspire-handreiking#53]
[SDS voorbeeld metadata](https://docs.geostandaarden.nl/eu/INSPIRE-handreiking/media/Voorbeeld_Metadata_Services_2022_max.xml) niet valide, link naar qualityOfService codelist niet correct. 

Gebruikte link is `http://inspire.ec.europa.eu/metadatacodelist/QualityOfServiceCriteriaCode` maar moet zijn `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria`, zie https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299

Zie ook gerelateerd issue met zelfde verwisseling in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/880. 

(Aanname is dat de situatie in [ets-repository](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299) de correcte situatie is)

**Comment by arbakker** [comment]
NB gelinkte issue bestaat niet meer want issues zijn uitgezet op dat repo ten faveure van https://github.com/INSPIRE-MIF/helpdesk-validator/issues

**Comment by PB-GNM** [comment]
Dit lijkt hetzelfde als #52 en is dus ook gesloten.
