### ISSUE TITLE
Find your scope is uit productie gehaald, dus weghalen uit handreiking

### ISSUE THREAD

**Issue by wboersma** [Geonovum/inspire-handreiking#58]
De [Find your scope](https://inspire-regadmin.jrc.ec.europa.eu/dataspecification/FindYourScope.action) is uit productie gehaald, zie https://github.com/INSPIRE-MIF/helpdesk/issues/177#issuecomment-1983085624. 

Dus dit moet ook uit de handreiking worden gehaald in in 1.4 en 3.3

@PB-GNM kun jij dit aanpassen.

**Comment by PB-GNM** [comment]
Hoi Wideke,

Ik pak hem op.

Groet,
Pieter,

06-82899376

Van: Wideke Boersma ***@***.***>
Verzonden: woensdag 13 maart 2024 13:30
Aan: Geonovum/inspire-handreiking ***@***.***>
CC: Pieter Bresters ***@***.***>; Mention ***@***.***>
Onderwerp: [Geonovum/inspire-handreiking] Find your scope is uit productie gehaald, dus weghalen uit handreiking (Issue #58)


De Find your scope<https://inspire-regadmin.jrc.ec.europa.eu/dataspecification/FindYourScope.action> is uit productie gehaald, zie INSPIRE-MIF/helpdesk#177 (comment)<https://github.com/INSPIRE-MIF/helpdesk/issues/177#issuecomment-1983085624>.

Dus dit moet ook uit de handreiking worden gehaald in in 1.4 en 3.3

@PB-GNM<https://github.com/PB-GNM> kun jij dit aanpassen.

**Comment by PB-GNM** [comment]
Het is in de werkversie verwijderd in 1.4 en 3.3.
